name: attendance_management
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  gsheets: ^0.5.0
  easy_date_timeline: ^2.0.6
  connectivity_plus: ^6.1.3
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  dynamic_color: ^1.7.0
  another_flutter_splash_screen: ^1.2.1
  equatable: ^2.0.7
  skeletonizer: ^1.4.3
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/static/Roboto-Thin.ttf
          weight: 200
        - asset: assets/fonts/Roboto/static/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/static/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/static/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/static/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto/static/Roboto-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/static/Roboto-Black.ttf
          weight: 800

  assets:
    - env_keys.env
    - assets/
    - assets/images/misc/
    - assets/lotties/misc_module/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
